Nom = str(input("Nom du cours \n"))
PointCumule = int(input("Entrée les points accumulé"))
PointTotal = int(input("Saisire les point total accumulé"))
NombreRestant = int(input("Nombre restant"))
ponderation = int(input(""))